__variables:
  - &size [128, 256]
  - &mean [0.485, 0.456, 0.406]
  - &std [0.229, 0.224, 0.225]
  - &data_dir ./data/cityscapes_ss/
  - &n_classes 19

__particular_variables:
  - &feat_levels [3, 4, 5]

framework:
  type: SemSeg
  input_size: *size

data_pipeline:
  dataset:
    type: SemSegDataset
    data_dir: *data_dir
    transforms:
      train:
        - { type: Resize, scale_range: [0.5, 2.0] }
        - { type: RandomCrop, size: *size }
        - { type: RandomHorizontalFlip }
        - { type: PhotoMetricDistortion }
        - { type: Normalize, mean: *mean, std: *std }
      val:
        - { type: Resize, size: *size }
        - { type: Normalize, mean: *mean, std: *std }
      test:
        - { type: Normalize, mean: *mean, std: *std }
    use_pkl: true
  dataloader:
    batch_size: 16
    num_workers: 2

model:
  type: BiSeNetV2
  detail_branch:
    out_channels: [64, 64, &channels 128]
  semantic_branch:
    out_channels: &aux_channels [16, 32, 64, *channels]
  bga:
    in_channels: *channels
    out_channels: *channels
  head:
    in_channels: *channels
    mid_channels: 1024
    n_classes: *n_classes
  aux_head:
    in_channels: *aux_channels
    mid_channels: [16, 64, 128, 512]
    n_classes: *n_classes
  criterion:
    cls_loss: { type: OHEMCrossEntropyLoss, reduction: mean, ignore_index: 255 }
    aux_loss: { type: OHEMCrossEntropyLoss, reduction: mean, ignore_index: 255 }

optimizer:
  type: SGD
  lr: 0.025
  momentum: 0.9
  weight_decay: 0.0005
  multipliers:
    "backbone": { lr: 0.1 }

scheduler:
  type: PolynomialLR
  gamma: 0.9
  max_iterations: 40000

metrics:
  - type: MeanIoU
    n_classes: *n_classes
    labelmap_path: ./data/cityscapes_ss/labelmap.json
    ignore_index: 255
