__variables:
  - &size [512, 1024]
  - &mean [0.485, 0.456, 0.406]
  - &std [0.229, 0.224, 0.225]
  - &data_dir ./data/cityscapes_ss/
  - &n_classes 19

__particular_variables:
  - &feat_levels [3, 4, 5]

framework:
  type: SemSeg
  input_size: *size

data_pipeline:
  dataset:
    type: SemSegDataset
    data_dir: *data_dir
    transforms:
      train:
        - { type: PhotoMetricDistortion }
        - { type: Normalize, mean: *mean, std: *std }
        - { type: Resize, scale_range: [1.0, 4.0] }
        - { type: RandomCrop, size: *size }
        - { type: RandomHorizontalFlip }
        - { type: PixelwiseCutOff, p: [0.0, 0.1] }
      val:
        - { type: Normalize, mean: *mean, std: *std }
        - { type: Resize, size: *size }
      test:
        - { type: Normalize, mean: *mean, std: *std }
        - { type: Resize, size: *size }
  dataloader:
    batch_size: 16
    num_workers: 2

model:
  type: BiSeNetV2
  detail_branch:
    out_channels: [64, 64, &channels 128]
  semantic_branch:
    out_channels: &aux_channels [16, 32, 64, *channels]
  bga:
    in_channels: *channels
    out_channels: *channels
  head:
    in_channels: *channels
    mid_channels: 512
    n_classes: *n_classes
    input_size: *size
  aux_head:
    in_channels: *aux_channels
    mid_channels: [32, 64, 128, 256]
    n_classes: *n_classes
    input_size: *size
  criterion:
    cls_loss: { type: CrossEntropyLoss, reduction: mean, ignore_index: 255 }
    aux_loss: { type: CrossEntropyLoss, reduction: mean, ignore_index: 255 }

optimizer:
  type: SGD
  param_args:
    lr:
      bias: 2.
    weight_decay:
      bias: 0.
  lr: 0.05
  momentum: 0.9
  weight_decay: 0.0005

scheduler:
  type: PolynomialScheduler
  gamma: 0.9
  n_iterations: 1500000

metrics:
  - type: MeanIoU
    n_classes: *n_classes
    labelmap_path: ./data/cityscapes_ss/info.json
    ignore_index: 255
