__variables:
  - &size [512, 1024]
  - &mean [0.485, 0.456, 0.406]
  - &std [0.229, 0.224, 0.225]
  - &data_dir ./data/cityscapes_ss/
  - &n_classes 19

__particular_variables:
  - &feat_levels [2, 4, 5]
  - &dilation [false, true, true]
  - &bins [1, 12, 24, 36]

framework:
  type: SemSeg
  input_size: *size

data_pipeline:
  dataset:
    type: SemSegDataset
    data_dir: *data_dir
    transforms:
      train:
        - { type: PhotoMetricDistortion }
        - { type: Normalize, mean: *mean, std: *std }
        - { type: Resize, scale_range: [1.0, 4.0] }
        - { type: RandomCrop, size: *size }
        - { type: RandomHorizontalFlip }
        - { type: PixelwiseCutOff, p: [0.0, 0.1] }
      val:
        - { type: Normalize, mean: *mean, std: *std }
        - { type: Resize, size: *size }
      test:
        - { type: Normalize, mean: *mean, std: *std }
        - { type: Resize, size: *size }
  dataloader:
    batch_size: 2
    num_workers: 2

model:
  type: DeepLabV3P
  feat_levels: *feat_levels
  backbone:
    type: ResNet
    depth: 50
    weights: default
    frozen_stages: 1
    replace_stride_with_dilation: *dilation
  head:
    mid_channels: 512
    low_out_channels: 48
    bins: *bins
    n_classes: *n_classes
    input_size: *size
  aux_head:
    mid_channels: 256
    n_classes: *n_classes
    input_size: *size
  criterion:
    cls_loss: { type: CrossEntropyLoss, reduction: mean, ignore_index: 255 }
    aux_loss: { type: CrossEntropyLoss, reduction: mean, ignore_index: 255 }

optimizer:
  type: SGD
  param_args:
    lr:
      backbone: 0.1
      bias: 2.
    weight_decay:
      bias: 0.
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0005

scheduler:
  type: WarmupExponentialLR
  gamma: 0.96
  warmup_interval: 3
  warmup_start_factor: 0.3

metrics:
  - type: MeanIoU
    n_classes: *n_classes
    labelmap_path: ./data/cityscapes_ss/info.json
    ignore_index: 255
