__variables:
  - &size [512, 1024]
  - &mean [0.485, 0.456, 0.406]
  - &std [0.229, 0.224, 0.225]
  - &data_dir ./data/cityscapes_ss/
  - &n_classes 19

__particular_variables:
  - &feat_levels [2, 4, 5]
  - &dilation [false, true, true]
  - &bins [1, 12, 24, 36]

framework:
  type: SemSeg
  input_size: *size

data_pipeline:
  dataset:
    type: SemSegDataset
    data_dir: *data_dir
    transforms:
      train:
        - { type: Resize, scale_range: [0.5, 2.0] }
        - { type: RandomCrop, size: *size }
        - { type: RandomHorizontalFlip }
        - { type: PhotoMetricDistortion }
        - { type: Normalize, mean: *mean, std: *std }
      val:
        - { type: Resize, size: *size }
        - { type: Normalize, mean: *mean, std: *std }
      test:
        - { type: Normalize, mean: *mean, std: *std }
    use_pkl: true
  dataloader:
    batch_size: 2
    num_workers: 2

model:
  type: DeepLabV3P
  feat_levels: *feat_levels
  backbone:
    type: ResNet
    depth: 50
    weights: default
    replace_stride_with_dilation: *dilation
  head:
    mid_channels: 512
    low_out_channels: 48
    bins: *bins
    n_classes: *n_classes
  aux_head:
    mid_channels: 256
    n_classes: *n_classes  
  criterion:
    cls_loss: { type: OHEMCrossEntropyLoss, reduction: mean, ignore_index: 255 }
    aux_loss: { type: OHEMCrossEntropyLoss, reduction: mean, ignore_index: 255 }
  replace:
    mode: WS+GN
    num_groups: 32

optimizer:
  type: SGD
  lr: 0.025
  momentum: 0.9
  weight_decay: 0.0005

scheduler:
  type: PolynomialLR
  gamma: 0.9
  max_iterations: 160000

metrics:
  - type: MeanIoU
    n_classes: *n_classes
    labelmap_path: ./data/cityscapes_ss/labelmap.json
    ignore_index: 255
