__variables:
  - &size [512, 1024]
  - &mean [0.485, 0.456, 0.406]
  - &std [0.229, 0.224, 0.225]
  - &data_dir ./data/cityscapes_ss/
  - &n_classes 20

__particular_variables:
  - &feat_sizes [3, 4, 5, 6, 7]

framework:
  type: SemSeg
  input_size: *size

data_pipeline:
  dataset:
    type: SemSegDataset
    data_dir: *data_dir
    transforms:
      train:
        - { type: PhotoMetricDistortion }
        - { type: Normalize, mean: *mean, std: *std }
        - { type: RandomExpand, ratio_range: [1.0, 2.0] }
        - { type: RandomMinAreaCrop, min_areas: [0.3, 0.5, 0.7, 0.9] }
        - { type: Resize, size: *size }
        - { type: RandomHorizontalFlip }
        - { type: PixelwiseCutOff, p: [0.0, 0.15] }
      val:
        - { type: Normalize, mean: *mean, std: *std }
        - { type: Resize, size: *size }
      test:
        - { type: Normalize, mean: *mean, std: *std }
        - { type: Resize, size: *size }
  dataloader:
    batch_size: 4
    num_workers: 2

model:
  type: EfficientSeg
  size: d0
  backbone:
    type: EfficientNet
    weights: default
    frozen_stages: 1
    extra_mode: pool
  n_classes: *n_classes
  feat_sizes: *feat_sizes
  output_size: *size
  criterion:
    cls_loss: { type: CrossEntropyLoss, reduction: mean }

optimizer:
  type: SGD
  param_args:
    lr:
      backbone: 0.1
      bias: 2.
      gate_weights: 2.
    weight_decay:
      bias: 0.
      gate_weights: 0.
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0005

scheduler:
  type: WarmupMultiStepLR
  milestones: [40, 60]
  gamma: 0.1
  warmup_interval: 3
  warmup_start_factor: 0.3

metrics:
  - type: MeanIoU
    n_classes: *n_classes
    labelmap_path: ./data/cityscapes_ss/info.json
