__variables:
  - &size [512, 1024]
  - &mean [0.485, 0.456, 0.406]
  - &std [0.229, 0.224, 0.225]
  - &data_dir ./data/cityscapes_ss/
  - &n_classes 19

__particular_variables:
  - &feat_levels [3, 4, 5, 6, 7]

framework:
  type: SemSeg
  input_size: *size

data_pipeline:
  dataset:
    type: SemSegDataset
    data_dir: *data_dir
    transforms:
      train:
        - { type: PhotoMetricDistortion }
        - { type: Normalize, mean: *mean, std: *std }
        - { type: Resize, scale_range: [1.0, 4.0] }
        - { type: RandomCrop, size: *size }
        - { type: RandomHorizontalFlip }
        - { type: PixelwiseCutOff, p: [0.0, 0.1] }
      val:
        - { type: Normalize, mean: *mean, std: *std }
        - { type: Resize, size: *size }
      test:
        - { type: Normalize, mean: *mean, std: *std }
        - { type: Resize, size: *size }
  dataloader:
    batch_size: 8
    num_workers: 2

model:
  type: EfficientSeg
  size: d4
  backbone:
    type: EfficientNet
    weights: default
    frozen_stages: 1
  backbone:
    type: EfficientNet
    weights: default
    frozen_stages: 1
  extra:
    type: ExtraPool
    feat_levels: *feat_levels
  neck:
    feat_levels: *feat_levels
  head:
    feat_levels: *feat_levels
    n_classes: *n_classes
    input_size: *size
  criterion:
    cls_loss: { type: CrossEntropyLoss, reduction: mean, ignore_index: 255 }
  replace_bn_to_wsgn: true

optimizer:
  type: SGD
  param_args:
    lr:
      backbone: 0.1
      bias: 2.
      gate_weights: 2.
    weight_decay:
      bias: 0.
      gate_weights: 0.
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0005

scheduler:
  type: WarmupExponentialLR
  gamma: 0.96
  warmup_interval: 3
  warmup_start_factor: 0.3

metrics:
  - type: MeanIoU
    n_classes: *n_classes
    labelmap_path: ./data/cityscapes_ss/info.json
    ignore_index: 255
