__variables:
  - &size [512, 1024]
  - &mean [0.485, 0.456, 0.406]
  - &std [0.229, 0.224, 0.225]
  - &data_dir ./data/cityscapes_ss/
  - &n_classes 19

__particular_variables:
  - &bins [1, 2, 3, 6]

framework:
  type: SemSeg
  input_size: *size

data_pipeline:
  dataset:
    type: SemSegDataset
    data_dir: *data_dir
    transforms:
      train:
        - { type: PhotoMetricDistortion }
        - { type: Normalize, mean: *mean, std: *std }
        - { type: Resize, scale_range: [1.0, 4.0] }
        - { type: RandomCrop, size: *size }
        - { type: RandomHorizontalFlip }
      val:
        - { type: Normalize, mean: *mean, std: *std }
        - { type: Resize, size: *size }
      test:
        - { type: Normalize, mean: *mean, std: *std }
        - { type: Resize, size: *size }
  dataloader:
    batch_size: 2
    num_workers: 2

model:
  type: PSPNet
  feat_levels: [4, 5]
  backbone:
    type: ResNet
    depth: 50
    weights: default
    frozen_stages: -1
    replace_stride_with_dilation: [false, true, true]
  head:
    mid_channels: 512
    bins: *bins
    n_classes: *n_classes
    input_size: *size
  aux_head:
    mid_channels: 256
    n_classes: *n_classes
    input_size: *size    
  criterion:
    cls_loss: { type: CrossEntropyLoss, reduction: mean, ignore_index: 255 }
    aux_loss: { type: CrossEntropyLoss, reduction: mean, ignore_index: 255 }
  replace_bn_to_wsgn: true

optimizer:
  type: SGD
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0005

scheduler:
  type: PolynomialScheduler
  min_factor: 0.01
  gamma: 0.9
  n_iterations: 40000

metrics:
  - type: MeanIoU
    n_classes: *n_classes
    labelmap_path: ./data/cityscapes_ss/info.json
    ignore_index: 255
